brace_style = "PreferSameLine"
combine_control_expr = false
condense_wildcard_suffixes = true
comment_width = 120
edition = "2024"
enum_discriminant_align_threshold = 32
error_on_line_overflow = true
error_on_unformatted = true
fn_call_width = 64
fn_single_line = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
group_imports = "StdExternalCrate"
hard_tabs = false
hex_literal_case = "Lower"
imports_granularity = "Module"
imports_layout = "HorizontalVertical"
match_arm_blocks = false
match_block_trailing_comma = true
max_width = 120
newline_style = "Unix"
overflow_delimiter_expr = true
reoder_impl_items = true
short_array_element_width_threshold = 16
single_line_if_else_max_width = 0
single_line_let_else_max_width = 64
skip_macro_invocations = []
struct_field_align_threshold = 32
struct_lit_single_line = true
struct_lit_width = 32
struct_variant_width = 0
style_edition = "2024"
trailing_comma = "Always"
trailing_semicolon = true
unstable_features = true
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
